# Generated by Django 4.2.5 on 2025-09-18 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lawyer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.TextField()),
                ("email", models.TextField(unique=True)),
                ("phone_number", models.TextField()),
                ("license_number", models.TextField(unique=True)),
                ("professional_information", models.TextField(blank=True, null=True)),
                ("years_of_experience", models.IntegerField(null=True)),
                ("primary_practice_area", models.TextField(blank=True, null=True)),
                ("practice_location", models.TextField(blank=True, null=True)),
                ("working_court", models.TextField(blank=True, null=True)),
                ("specialization_document", models.TextField(blank=True, null=True)),
                ("education_document", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
