# Generated by Django 5.0 on 2025-09-12 00:04

import apps.documents.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="file",
            field=models.FileField(
                help_text="Upload PDF file only. Maximum file size: 20MB",
                upload_to="documents/",
                validators=[
                    apps.documents.validators.validate_pdf_file,
                    apps.documents.validators.validate_file_size,
                ],
            ),
        ),
    ]
