# Generated by Django 4.2.5 on 2025-09-18 11:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserChat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_text_input", models.TextField(blank=True, null=True)),
                ("ai_text_output", models.TextField(blank=True, null=True)),
                ("user_document_submission", models.TextField(blank=True, null=True)),
                ("chatbot_document", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
